- name: get gnome power settings
  shell: gsettings get org.gnome.settings-daemon.plugins.power active
  register: r_gnome_power
  changed_when: no
- set_fact:
    r_gnome_power_active: "{{ r_gnome_power.stdout }}"
- name: set gnome power settings
  shell: gsettings set org.gnome.settings-daemon.plugins.power active false
  when: r_gnome_power_active != false

- name: get gnome blank timeout
  shell: gsettings get org.gnome.desktop.session idle-delay
  register: r_gnome_blanktimeout
  changed_when: no
- set_fact:
    r_gnome_blanktimeout_value: "{{ r_gnome_blanktimeout.stdout }}"
- name: set gnome blank timout
  shell: gsettings set org.gnome.desktop.session idle-delay 0
  when: r_gnome_power_active != 0