- hosts: localhost
  connection: local
  run_once: true
  vars:
#    somevar: example
#    user: dev
    user: "{{ lookup('env','USER') }}"
    homedir: "{{ lookup('env','HOME') }}"
    git_name: "Till Hoffmann"
    git_mail: "till.hoffmann@enforge.de"
    nodejs_version:   "12.x"
    golang_version:   "1.13.1"
    gotask_version:  "2.7.1"
    minikube_version: "1.6.1"
    gnome_favorites:
        - org.gnome.Terminal.desktop
        - org.gnome.Nautilus.desktop
        - firefox.desktop
        - code.desktop
        - git-cola.desktop

# prerequisites
#    - installed ansible
#    - internet connection (running tproxy)
#    - sudo installed
#    - user dev in suders list (remove task "append 'sudo' to groups the user ...")
#    - gnome installed
# -> see ./prerequisites.sh

  roles:
    - l_common
    - l_dev
    - l_docker
    - l_minikube
    - l_vm
    - l_custom
