- hosts: localhost
  connection: local
  run_once: true
  #become: true
  #become_method: sudo
  vars:
#    somevar: example
#    user: dev
    user: "{{ lookup('env','USER') }}"
    homedir: "{{ lookup('env','HOME') }}"
    git_name: "Till Hoffmann"
    git_mail: "till.hoffmann@enforge.de"
    nodejs_version: node_12.x
    gnome_favorites:
        - org.gnome.Terminal.desktop
        - org.gnome.Nautilus.desktop
        - firefox.desktop
        - code.desktop
        - git-cola.desktop

# prerequisites
#    - installed ansible
#    - internet connection (running tproxy)
#    - sudo installed
#    - user dev in suders list (remove task "append 'sudo' to groups the user ...")
#    - gnome installed

  roles:
    - l_common
    - l_dev
    - l_docker
    - l_minikube
    - l_vm
    - l_custom
#    - l_extended
