- debug:
    msg: "The hostname is {{ ansible_facts['nodename'] }} and the OS is {{ ansible_facts['distribution'] }}."
- debug:
    msg: "The user is {{ user }}"

- name: update apt and update existing packages
  become: true
  apt:
    update_cache: yes
    cache_valid_time: 86400 #One day
    upgrade: full
- name: install snapd
  become: true
  apt:
    name: snapd

- name: Append 'sudo' to groups the user '{{ user }}'' is in
  become: true
  user:
    name: "{{ user }}"
    groups: sudo
    append: yes

- name: install basic system tools
  become: true
  apt:
    name:
      - curl
      - wget
      - dnsutils # for nslookup
      - net-tools # for netstat

- name: uninstall games
  become: true
  apt:
    state: absent
    name:
      - aisleriot
      - five-or-more
      - gnome-klotski
      - gnome-mines
      - gnome-robots
      - gnome-taquin
      - hitori
      - lightsoff
      - swell-foop
      - four-in-a-row
      - gnome-mahjongg
      - gnome-nibbles
      - gnome-sudoku
      - gnome-tetravex
      - iagno
      - quadrapassel
      - tali

- name: uninstall old dependencies
  become: true
  apt:
    autoremove: yes

- include_tasks: subtasks/subtask_add_path.yml
  vars:
    extra_path: "{{ item }}"
  with_items:
    - /usr/local/sbin
    - /usr/local/bin
    - /usr/sbin
    - /usr/bin
    - /sbin
    - /bin
    - /snap/bin

- include_tasks: subtasks/subtask_remove_path.yml
  vars:
    extra_path: "{{ item }}"
  with_items:
    - /usr/games
    - /usr/local/games

- name: remove game files&folders from disk
  become: true
  file:
    state: absent
    path: "{{ item }}"
  with_items:
    - "/usr/games"
    - "/usr/local/games"

- name: install dependencies for extensions
  become: true
  apt:
    name:
      - gir1.2-gtop-2.0
      - gir1.2-networkmanager-1.0
- name: install gnome extensions
  include_tasks: subtasks/subtask_gnome_extension.yml
  vars:
    gnome_extension_ids:
      - 39 #Put-Windows
      - 104 #NetSpeed
      - 120 #System-Monitor

- name: install pdf reader
  become: true
  apt:
    name:
      - evince #for pdfs
