- name: install vscode
  become: true
  become_method: sudo
  snap:
    name: code
    classic: yes
- include_tasks: subtasks/subtask_vscode_extension.yml
  vars:
    extension: "{{ item }}"
  with_items:
    - ms-azuretools.vscode-docker
    - ms-python.python
    - ms-vscode.Go
    - tomoki1207.pdf
- name: configure vscode
  # to fix the problem with altgr behaving as left-arrow for example
  shell: 'echo -e ''{\n  "git.autofetch": true,\n  "keyboard.dispatch": "keyCode"\n}'' > ~/.config/Code/User/settings.json'
  #///TODO improve this maybe?
- name: install git
  become: true
  become_method: sudo
  apt:
    name:
      - git
- name: configure git global values
  become: true
  become_user: "{{ user }}"
  block:
    - git_config:
        name: user.name
        scope: global
        value: "{{ git_name }}"
    - git_config:
        name: user.email
        scope: global
        value: "{{ git_mail }}"

- name: install gitcola
  become: true
  become_method: sudo
  apt:
    name:
      - git-cola

- name: install pip
  become: true
  become_method: sudo
  apt:
    name: python-pip

- name: check if go is installed
  stat:
    path: /usr/local/go/bin
  register: go_result
- name: install golang
  become: true
  become_method: sudo
  shell: curl -L https://dl.google.com/go/go1.13.1.linux-amd64.tar.gz -o ./go.tar.gz && sudo tar -C /usr/local -xzf ./go.tar.gz && rm ./go.tar.gz
  when: go_result.stat.exists == false

- name: check if go-task is installed
  stat:
    path: /usr/local/bin/task
  register: gotask_result
- name: install go-task
  become: true
  become_method: sudo
  shell: curl -L https://github.com/go-task/task/releases/download/v2.7.1/task_linux_amd64.deb -o ./go-task.deb && sudo dpkg -i ./go-task.deb && sudo rm ./go-task.deb
  when: gotask_result.stat.exists == false
  #task is added to /usr/local/bin/ and is thus automatically added to path

- include_tasks: subtasks/subtask_add_path.yml
  vars:
    extra_path: "{{ item }}"
  with_items:
    - /snap/bin
    - /usr/local/go/bin

#///TODO add checkups (do only once) for nodejs
- name: add nodejs repo-key
  become: true
  become_method: sudo
  shell: curl -sSL https://deb.nodesource.com/gpgkey/nodesource.gpg.key | sudo apt-key add -
- name: add nodejs repo to sources.list
  become: true
  become_method: sudo
  shell: echo "deb https://deb.nodesource.com/{{ nodejs_version }} $(lsb_release -s -c) main" | sudo tee /etc/apt/sources.list.d/nodesource.list
- name: add nodejs src-repo to sources.list
  become: true
  become_method: sudo
  shell: echo "deb-src https://deb.nodesource.com/{{ nodejs_version }} $(lsb_release -s -c) main" | sudo tee -a /etc/apt/sources.list.d/nodesource.list
- name: install nodejs
  become: true
  become_method: sudo
  apt:
    update_cache: yes
    cache_valid_time: 86400 #One day
    name:
      - nodejs