- name: install dependencies for nodejs
  become: true
  apt:
    name:
      - apt-transport-https
      - gnupg2
    state: present
- name: add nodejs repo-key
  become: true
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present
- name: add nodejs repo to apt
  become: true
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - "deb https://deb.nodesource.com/node_{{ nodejs_version }} {{ ansible_distribution_release }} main"
    - "deb-src https://deb.nodesource.com/node_{{ nodejs_version }} {{ ansible_distribution_release }} main"
  register: node_repo
- name: update apt cache if repo was added
  become: true
  apt:
    update_cache: yes
  when: node_repo.changed
- name: install nodejs with npm
  become: true
  apt:
    name: "nodejs={{ nodejs_version|regex_replace('x', '') }}*"
    state: present
