# install docker-ce
- name: install prerequisites for docker
  become: true
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - gnupg2
      - software-properties-common
- name: add docker repo-key to apt
  become: true
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present
- name: add docker repo to apt
  become: true
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present
  register: docker_repo
- name: update apt cache if repo was added
  become: true
  apt: update_cache=yes
  when: docker_repo.changed
- name: install docker
  become: true
  apt:
    name: docker-ce
    state: present
- name: append 'docker' to groups the user '{{ user }}' is in
  become: true
  user:
    name: "{{ user }}"
    groups: docker
    append: yes
