- name: install prerequisites for docker
  become: true
  become_method: sudo
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - gnupg2
      - software-properties-common
- name: add apt signing key for docker repo
  become: true
  become_method: sudo
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present
- name: add repository
  become: true
  become_method: sudo
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present
- name: update apt and install docker
  become: true
  become_method: sudo
  apt:
    update_cache: yes
    name: docker-ce
- name: append 'docker' to groups the user '{{ user }}' is in
  become: true
  become_method: sudo
  user:
    name: "{{ user }}"
    groups: docker
    append: yes