- name: install kvm
  become: true
  apt:
    name:
      - qemu-kvm
      - libvirt-clients
      - libvirt-daemon-system
      - virt-manager
- name: append 'libvirt' and 'libvirt-qemu' to groups the user '{{ user }}' is in
  become: true
  user:
    name: "{{ user }}"
    groups: libvirt,libvirt-qemu
    append: yes
- name: install minikube
  become: true
  apt:
    deb: https://github.com/kubernetes/minikube/releases/download/v{{ minikube_version }}/minikube_{{ minikube_version }}.deb
- name: check if docker-machine-driver is installed
  stat:
    path: /usr/local/bin/docker-machine-driver-kvm2
  register: docker_machine_driver_result
- name: install docker-machine-driver for minikube
  become: true
  shell: curl -LO https://storage.googleapis.com/minikube/releases/latest/docker-machine-driver-kvm2 && install docker-machine-driver-kvm2 /usr/local/bin/ && rm docker-machine-driver-kvm2
  args:
    warn: false
  when: docker_machine_driver_result.stat.exists == false
#- name: disable apparmor for libvirtd
#  file: src=/etc/apparmor.d/usr.sbin.libvirtd dest=/etc/apparmor.d/disable/usr.sbin.libvirtd state=link
#  diabled, as this must be run on every startup
#    - name: start minikube
#      shell: minikube start --vm-driver=kvm2
- debug:
    msg: Please run minikube start --vm-driver=kvm2 at least once
- name: check if kubectl is installed
  become: true
  stat:
    path: /usr/local/bin/kubectl
  register: kubectl_result
- name: install kubectl
  become: true
  shell: curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl && chmod +x ./kubectl && sudo mv ./kubectl /usr/local/bin/kubectl
  args:
    warn: false
  when: kubectl_result.stat.exists == false


# - debug:
#     msg: "Please restart the host now. (Due to disabling apparmor for libvirt.)"
# - name: disable apparmor
#   become: true
#   shell: systemctl stop apparmor && systemctl disable apparmor
