- debug:
    msg: "The hostname is {{ ansible_facts['nodename'] }} and the OS is {{ ansible_facts['distribution'] }}."
- debug:
    msg: "The user is {{ user }}"

- name: install chocolatey
  win_shell: Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
- name: install scoop
  win_shell: Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://get.scoop.sh')

- name: Download the 7-Zip package
  win_get_url:
    url: https://www.7-zip.org/a/7z1701-x64.msi
    dest: C:\temp\7z.msi
- name: Check if 7-Zip is already installed
  win_reg_stat:
    name: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{23170F69-40C1-2702-1701-000001000000}
  register: 7zip_installed
- name: Ensure 7-Zip is installed
  win_command: C:\Windows\System32\msiexec.exe /i C:\temp\7z.msi /qn /norestart
  when: 7zip_installed.exists == false
- name: Delete 7-Zip package file
  win_shell: rm C:\temp\7z.msi