- name: Check if gotask is installed
  stat:
    path: /usr/local/bin/task
  register: gotask_exists
  changed_when: false
- name: Check if gotask has correct version
  shell: task --version 2>&1 | rev | cut -d " " -f 1 | rev
  when: gotask_exists.stat.exists == true
  register: gotask_currentversion
  changed_when: false
- name: Install gotask
  become: true
  apt:
    deb: https://github.com/go-task/task/releases/download/v{{ gotask_version }}/task_linux_amd64.deb
    force: true # for enabling downgrades
  when: "(gotask_exists.stat.exists == false) or (gotask_version != gotask_currentversion.stdout)"
  # task is added to /usr/local/bin/ and is thus automatically added to path
- name: Install task completion for bash
  become: true
  get_url:
    url: "https://raw.githubusercontent.com/go-task/task/v{{ gotask_version }}/completion/bash/task.bash"
    dest: "/etc/bash_completion.d/task.bash"
    force: yes
  when: "(gotask_exists.stat.exists == false) or (gotask_version != gotask_currentversion.stdout)"
