- name: Install minikube
  become: true
  apt:
    deb: https://github.com/kubernetes/minikube/releases/download/v{{ minikube_version }}/minikube_{{ minikube_version }}-0_amd64.deb
- name: Set default driver for minikube
  shell: minikube config set driver docker
- name: Start minikube
  shell: minikube start --extra-config=apiserver.service-node-port-range=1-65535
- name: Set addons for minikube
  shell: minikube addons enable ingress
